//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vapor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Color : global::System.Configuration.ApplicationSettingsBase {
        
        private static Color defaultInstance = ((Color)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Color())));
        
        public static Color Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("177, 251, 80")]
        public global::System.Drawing.Color StatusIngameFore {
            get {
                return ((global::System.Drawing.Color)(this["StatusIngameFore"]));
            }
            set {
                this["StatusIngameFore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color StatusIngameBack {
            get {
                return ((global::System.Drawing.Color)(this["StatusIngameBack"]));
            }
            set {
                this["StatusIngameBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("111, 189, 255")]
        public global::System.Drawing.Color StatusOnlineFore {
            get {
                return ((global::System.Drawing.Color)(this["StatusOnlineFore"]));
            }
            set {
                this["StatusOnlineFore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color StatusOnlineBack {
            get {
                return ((global::System.Drawing.Color)(this["StatusOnlineBack"]));
            }
            set {
                this["StatusOnlineBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("137, 137, 137")]
        public global::System.Drawing.Color StatusOfflineFore {
            get {
                return ((global::System.Drawing.Color)(this["StatusOfflineFore"]));
            }
            set {
                this["StatusOfflineFore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color StatusOfflineBack {
            get {
                return ((global::System.Drawing.Color)(this["StatusOfflineBack"]));
            }
            set {
                this["StatusOfflineBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("251, 80, 80")]
        public global::System.Drawing.Color StatusBlockedFore {
            get {
                return ((global::System.Drawing.Color)(this["StatusBlockedFore"]));
            }
            set {
                this["StatusBlockedFore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color StatusBlockedBack {
            get {
                return ((global::System.Drawing.Color)(this["StatusBlockedBack"]));
            }
            set {
                this["StatusBlockedBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250, 218, 94")]
        public global::System.Drawing.Color StatusInvitedFore {
            get {
                return ((global::System.Drawing.Color)(this["StatusInvitedFore"]));
            }
            set {
                this["StatusInvitedFore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color StatusInvitedBack {
            get {
                return ((global::System.Drawing.Color)(this["StatusInvitedBack"]));
            }
            set {
                this["StatusInvitedBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color FriendsFore {
            get {
                return ((global::System.Drawing.Color)(this["FriendsFore"]));
            }
            set {
                this["FriendsFore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color FriendsBack {
            get {
                return ((global::System.Drawing.Color)(this["FriendsBack"]));
            }
            set {
                this["FriendsBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color FriendsHigh {
            get {
                return ((global::System.Drawing.Color)(this["FriendsHigh"]));
            }
            set {
                this["FriendsHigh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("135, 169, 107")]
        public global::System.Drawing.Color StatusRequestingFore {
            get {
                return ((global::System.Drawing.Color)(this["StatusRequestingFore"]));
            }
            set {
                this["StatusRequestingFore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color StatusRequestingBack {
            get {
                return ((global::System.Drawing.Color)(this["StatusRequestingBack"]));
            }
            set {
                this["StatusRequestingBack"] = value;
            }
        }
    }
}
